export { Header } from "./components/header.js";
export { Hero } from "./components/hero.js";
export { Featured } from "./components/featured.js";
export { Categories } from "./components/categories.js";
export { Hotels } from "./components/hotels.js";
export { Cars } from "./components/cars.js";
export { Testimonials } from "./components/testimonials.js";
export { Blog } from "./components/blog.js";
export { Footer } from "./components/footer.js";
